=== prachispanse/Web-Development-Projects/clubServer/clubUsersSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "",
    "title":"",
    "description":"",
    "type": "object",
    "properties": {
        "firstName": {
			"description": "Users first name",
            "type": "string",
            "minLength":1,
			"maxLength":20
            },
		"lastName": {
			"description": "Users last name",
            "type": "string",
            "minLength":1,
			"maxLength":20
            },
		"role": {
			"description": "Users role",
            "type": "string",
            "minLength":1,
			"maxLength":10
            },
		"email": {
			"description": "Users email",
            "type": "string",
            "minLength":1,
			"maxLength":30
            },
		"password": {
			"description": "Users password",
            "type": "string",
            "minLength":1,
			"maxLength":20
            }
		
       }
}

=== prachispanse/Web-Development-Projects/clubServer/clubUsersHash.json
[
  {
    "firstName": "Melia",
    "lastName": "Barker",
    "email": "tirrivees1820@outlook.com",
    "password": "$2a$13$YbM7H14OLVO9RRoaYL5pFOB2bucVAGi2SlCyY4C/qmhjqEzwA9V86",
    "role": "admin"
  },
  {
    "firstName": "Demetrice",
    "lastName": "Parker",
    "email": "chihuahua1899@gmail.com",
    "password": "$2a$13$gLgg.xSXBdnTQa3u4eRDz.MjsWHFvIWeml04MXr3dvNPKzUpRT7Ay",
    "role": "member"
  },
  {
    "firstName": "Ligia",
    "lastName": "Hudson",
    "email": "umbrate1989@yahoo.com",
    "password": "$2a$13$9uK1g3GKs8g1/hxQ6C6UtetOjU7j1buBuDgKQ4SJbvS3kB98HiWKC",
    "role": "member"
  },
  {
    "firstName": "Maisha",
    "lastName": "Hickman",
    "email": "bibiri1807@yandex.com",
    "password": "$2a$13$/eixoy8S3eQsloDSSHZOv.PJpLlTdFy8HGBc6t0AtRqafByKTyeR6",
    "role": "member"
  },
  {
    "firstName": "Cythia",
    "lastName": "Park",
    "email": "biune1929@gmail.com",
    "password": "$2a$13$.sEjA1pHWJROwVfYPEzBRO.K.XUKIihZyHwQOKD.Ps6HA6EXsFvJu",
    "role": "member"
  },
  {
    "firstName": "Arlie",
    "lastName": "Holt",
    "email": "aromatised1858@yandex.com",
    "password": "$2a$13$mgp1caTd5nZ2LM1ozrbhhesXXjQVtIGK8UAXw7bWPD8hqVf1onqsS",
    "role": "member"
  },
  {
    "firstName": "Andy",
    "lastName": "Morton",
    "email": "bayesian1899@outlook.com",
    "password": "$2a$13$pVGcIF9xN7C.BvV2pXaUU.I/adNPKsZB2B8oEjxL.O8.q2N8FQ/YC",
    "role": "member"
  },
  {
    "firstName": "Peg",
    "lastName": "Gardner",
    "email": "earrings1987@yandex.com",
    "password": "$2a$13$EvR31t69gWO93wY0Pjlrs.TPoxFUR5fPIeqEGoCPiy/xNTluTFuk2",
    "role": "member"
  },
  {
    "firstName": "Noble",
    "lastName": "Wilder",
    "email": "facer1912@yandex.com",
    "password": "$2a$13$FNTElBsQUID70oYwhX6eWeyo56Dy7wbXF4jkc9/k45yQTqs7zUU06",
    "role": "member"
  },
  {
    "firstName": "Willow",
    "lastName": "Trevino",
    "email": "nodes1883@yahoo.com",
    "password": "$2a$13$/Z3OuaFsBLza1kv6Vupo4O4T70diwDJ/lE23AtYRmJgTmfDYGyLaC",
    "role": "member"
  },
  {
    "firstName": "Corrinne",
    "lastName": "Curtis",
    "email": "boisset1829@live.com",
    "password": "$2a$13$h3Lc0SQbQsxEbtWgQLvZTessXDB6G3LZ/ZC1IQVk4sKaOZQZuG0De",
    "role": "member"
  },
  {
    "firstName": "Joseph",
    "lastName": "Brock",
    "email": "utilizer1910@live.com",
    "password": "$2a$13$rT79ykJWrLFVO98rmsvPwu31vq3c4MqbY7FTkVYlwoJvirNL7FnB6",
    "role": "member"
  },
  {
    "firstName": "Daron",
    "lastName": "Stevens",
    "email": "pedocalcic1982@outlook.com",
    "password": "$2a$13$oseNr7R1jnLYhpSoTRGqo.aoRNF.Xk4CTQTZumNRZ049P6LkglsjC",
    "role": "member"
  },
  {
    "firstName": "Anamaria",
    "lastName": "Grant",
    "email": "downtown1843@live.com",
    "password": "$2a$13$ECvvV6nqxCZB0S3/haXgw.ak60VF6EXbBAKBs.zuhLLtnpH0ZPAx6",
    "role": "member"
  },
  {
    "firstName": "Leonard",
    "lastName": "Shepherd",
    "email": "thrower1972@yahoo.com",
    "password": "$2a$13$MjcXfVF6MkkNKgHzd7DtqO03OobYhgItZe8G34LaPL6/iM3iyuTtG",
    "role": "member"
  },
  {
    "firstName": "Belia",
    "lastName": "Monroe",
    "email": "cranky1882@gmail.com",
    "password": "$2a$13$FMusrzRbgQpluvjjqIh5Puz347ndeESLTade.PXoHsov48BVq63oa",
    "role": "member"
  },
  {
    "firstName": "Stacey",
    "lastName": "Calderon",
    "email": "marsileaceae1910@gmail.com",
    "password": "$2a$13$bspmNasuqN7/1Bks0CChbOZAqX7NqzAF9eBkZISLVDKlbG6DSZO2q",
    "role": "member"
  },
  {
    "firstName": "Bob",
    "lastName": "Fitzgerald",
    "email": "burin1898@yahoo.com",
    "password": "$2a$13$03dm.md60GR/oN.b9sAtTOnRv55cIFohqKKtzElbCQj0aLai.AU8O",
    "role": "member"
  },
  {
    "firstName": "Albertina",
    "lastName": "Mclaughlin",
    "email": "drainpipe2041@yandex.com",
    "password": "$2a$13$6F6EqKEfMOnNsMU44fLYS.iPO.5QteYll/ZyvehP2.iEQ3dZKEWJq",
    "role": "member"
  },
  {
    "firstName": "Marg",
    "lastName": "Carney",
    "email": "ventages2031@yahoo.com",
    "password": "$2a$13$wLAocPPkjxlKlsMCf3fxc.rAhe3lHKJF4qmZ7Re6FdaAcT3uJUhfq",
    "role": "member"
  },
  {
    "firstName": "Jeffery",
    "lastName": "Charles",
    "email": "zaffer1889@live.com",
    "password": "$2a$13$YpwFctUsihlSkCGKPsPMcu6gmGwkwpMJUHq72QVwbLMB75FlD567y",
    "role": "member"
  },
  {
    "firstName": "Annett",
    "lastName": "Parsons",
    "email": "kurikata1944@yandex.com",
    "password": "$2a$13$acCiqFxMz1wcJR89IUnxrOm37yXZM2QfwKz7//7g8OeNy5s9FFkOW",
    "role": "member"
  },
  {
    "firstName": "Wilson",
    "lastName": "Sharpe",
    "email": "misunderstandable1916@live.com",
    "password": "$2a$13$4OlAZ7LtqG3QFxlRqh0maOKuGY/waVXUW38kVEue76Bn1HOUldPGG",
    "role": "member"
  },
  {
    "firstName": "Gertude",
    "lastName": "Ewing",
    "email": "althein1801@yahoo.com",
    "password": "$2a$13$Oi99geSoh/Ny4Vlo1B6H2u0z8rzUOCJ7KWNGBsqQ7GoYDPH09qGfK",
    "role": "member"
  },
  {
    "firstName": "Phil",
    "lastName": "Knowles",
    "email": "piscators1880@live.com",
    "password": "$2a$13$atxcF41JiLBVNwqMw.NWYu0LDbMjEghqyrdZnOb3zzuivghMePR3a",
    "role": "member"
  },
  {
    "firstName": "Catherina",
    "lastName": "Castillo",
    "email": "saltworker1892@live.com",
    "password": "$2a$13$LSRB8UeOZnTNBxSpZWhkrOoVSn/EfuS.uO2fsrF62YnSu18ghN/cO",
    "role": "member"
  },
  {
    "firstName": "Jim",
    "lastName": "Kennedy",
    "email": "speer2026@outlook.com",
    "password": "$2a$13$N6EN6Nib7UpLY3tKKyuxP.tcE9f/duibc9VRaSggsDIRdE44eo11O",
    "role": "member"
  },
  {
    "firstName": "Tula",
    "lastName": "Stafford",
    "email": "devoir1853@live.com",
    "password": "$2a$13$TonnoS2NYSU.v2lIT8ioYeaaTa.q5GaaMoli9IQ.jB6hzzXzW/y/.",
    "role": "member"
  },
  {
    "firstName": "Rachell",
    "lastName": "Harding",
    "email": "article1896@outlook.com",
    "password": "$2a$13$Qt5JKz6oMtFLaQtIPPKYn.HOFPeM/Sy513i0.DgfVaOuxn4prb6/a",
    "role": "member"
  },
  {
    "firstName": "Brandon",
    "lastName": "Monroe",
    "email": "article1821@live.com",
    "password": "$2a$13$DD10d7r25HAWVL7.zvrXuehH6a1AboxEMY/3roagWN1.nq3GTqiY6",
    "role": "member"
  },
  {
    "firstName": "Micha",
    "lastName": "Sanders",
    "email": "fewer1818@outlook.com",
    "password": "$2a$13$byD239KplQl9JF2Ixjqp.Oflj418013D8mwDDLlwEkFxWTrnbjZWm",
    "role": "member"
  },
  {
    "firstName": "Blake",
    "lastName": "Gray",
    "email": "occults1985@yandex.com",
    "password": "$2a$13$DwmFrFOj2Uo6MPaig7MmZemQB982rtsxZGUM9t.nuTqTT4edj56za",
    "role": "member"
  },
  {
    "firstName": "Karren",
    "lastName": "Crosby",
    "email": "harborers2000@live.com",
    "password": "$2a$13$RlC4JlCFK//f19Qvis4AVOwLvuYzLbgiJJ1S/f6ZHqU8RT74EWMe.",
    "role": "member"
  },
  {
    "firstName": "Faustino",
    "lastName": "Morris",
    "email": "bayard1928@outlook.com",
    "password": "$2a$13$81FX/eyXTijybl64Su7HMu.ehjIBjTURwv1AYy2kMIMw5TCw1VzY2",
    "role": "member"
  },
  {
    "firstName": "Claretta",
    "lastName": "Cummings",
    "email": "fish2004@gmail.com",
    "password": "$2a$13$LV6yHSo30KAfREtvxznSOuc2fVgHyaob9mJ7sXfiUbU2sgLbG6S9S",
    "role": "member"
  },
  {
    "firstName": "Carmen",
    "lastName": "Phillips",
    "email": "geometry1853@live.com",
    "password": "$2a$13$92Zy9lSp8xhVvFO09sR8AudeeN8.3rm9wsjtTqRoIjD1mDE6Ir4eS",
    "role": "member"
  },
  {
    "firstName": "Pamula",
    "lastName": "Holt",
    "email": "amperage1914@yandex.com",
    "password": "$2a$13$Xeewr1P5UqQx/KXM2Hn7AeCfmroQ2w5HMZ.Od2Ddf4R/TrzaQyHF.",
    "role": "member"
  },
  {
    "firstName": "Truman",
    "lastName": "Boyd",
    "email": "dustman2024@live.com",
    "password": "$2a$13$jMreQB6L.PT.3jgDT.TEaOWUWfZ3zIGdiKFlj7E5gpWAX5ZUVJLRa",
    "role": "member"
  },
  {
    "firstName": "Alphonso",
    "lastName": "Salazar",
    "email": "raddle2043@yandex.com",
    "password": "$2a$13$.v.L.rmthIKmuAZrSuhdj.a3PNL74WzYa6k8lj.nzzB5SZ9b4x54.",
    "role": "member"
  },
  {
    "firstName": "Isidra",
    "lastName": "O'neal",
    "email": "antonin2059@yahoo.com",
    "password": "$2a$13$hLtmmuXc5aa./08wy4Wq/uBzaGTMOBU9D7p8eOHZTyM3S1V9Qek8.",
    "role": "member"
  }
]
